<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction</a></span><ul class="toc-item"><li><span><a href="#Style" data-toc-modified-id="Style-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Style</a></span></li><li><span><a href="#Imports-and-data" data-toc-modified-id="Imports-and-data-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Imports and data</a></span></li><li><span><a href="#Load-from-SQL" data-toc-modified-id="Load-from-SQL-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Load from SQL</a></span></li><li><span><a href="#Load-old-data-from-pickles" data-toc-modified-id="Load-old-data-from-pickles-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Load old data from pickles</a></span></li></ul></li><li><span><a href="#Test" data-toc-modified-id="Test-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Test</a></span></li><li><span><a href="#Prices" data-toc-modified-id="Prices-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Prices</a></span><ul class="toc-item"><li><span><a href="#Clean" data-toc-modified-id="Clean-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Clean</a></span></li><li><span><a href="#Create-new-index,-and-diff" data-toc-modified-id="Create-new-index,-and-diff-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Create new index, and diff</a></span></li><li><span><a href="#Reindex-Price" data-toc-modified-id="Reindex-Price-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Reindex Price</a></span></li><li><span><a href="#Post-to-SQL" data-toc-modified-id="Post-to-SQL-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Post to SQL</a></span></li><li><span><a href="#To-pickle" data-toc-modified-id="To-pickle-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>To pickle</a></span></li><li><span><a href="#Reset-prices" data-toc-modified-id="Reset-prices-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>Reset prices</a></span></li></ul></li><li><span><a href="#Check-for-new-splits" data-toc-modified-id="Check-for-new-splits-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Check for new splits</a></span></li><li><span><a href="#Performance" data-toc-modified-id="Performance-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Performance</a></span><ul class="toc-item"><li><span><a href="#Functions" data-toc-modified-id="Functions-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Functions</a></span></li><li><span><a href="#Sort-old-index-old" data-toc-modified-id="Sort-old-index-old-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Sort old index old</a></span></li><li><span><a href="#load-in-data" data-toc-modified-id="load-in-data-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>load in data</a></span><ul class="toc-item"><li><span><a href="#Loc-relevant-symbols" data-toc-modified-id="Loc-relevant-symbols-5.3.1"><span class="toc-item-num">5.3.1&nbsp;&nbsp;</span>Loc relevant symbols</a></span></li></ul></li><li><span><a href="#Pull-out-new-data" data-toc-modified-id="Pull-out-new-data-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Pull out new data</a></span></li><li><span><a href="#Fill-ExDividendDate-and-map" data-toc-modified-id="Fill-ExDividendDate-and-map-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>Fill ExDividendDate and map</a></span></li><li><span><a href="#Find-and-clean-new-values" data-toc-modified-id="Find-and-clean-new-values-5.6"><span class="toc-item-num">5.6&nbsp;&nbsp;</span>Find and clean new values</a></span></li><li><span><a href="#To-numeric" data-toc-modified-id="To-numeric-5.7"><span class="toc-item-num">5.7&nbsp;&nbsp;</span>To numeric</a></span></li><li><span><a href="#Add-last-real-day-to-df_performance-for-interpolating" data-toc-modified-id="Add-last-real-day-to-df_performance-for-interpolating-5.8"><span class="toc-item-num">5.8&nbsp;&nbsp;</span>Add last real day to df_performance for interpolating</a></span></li><li><span><a href="#Create-new" data-toc-modified-id="Create-new-5.9"><span class="toc-item-num">5.9&nbsp;&nbsp;</span>Create new</a></span><ul class="toc-item"><li><span><a href="#Sort-index" data-toc-modified-id="Sort-index-5.9.1"><span class="toc-item-num">5.9.1&nbsp;&nbsp;</span>Sort index</a></span></li><li><span><a href="#Interpolate-null-values-by-symbol" data-toc-modified-id="Interpolate-null-values-by-symbol-5.9.2"><span class="toc-item-num">5.9.2&nbsp;&nbsp;</span>Interpolate null values by symbol</a></span></li></ul></li><li><span><a href="#Create-new" data-toc-modified-id="Create-new-5.10"><span class="toc-item-num">5.10&nbsp;&nbsp;</span>Create new</a></span><ul class="toc-item"><li><span><a href="#Sort-index-on-all_new" data-toc-modified-id="Sort-index-on-all_new-5.10.1"><span class="toc-item-num">5.10.1&nbsp;&nbsp;</span>Sort index on all_new</a></span></li></ul></li><li><span><a href="#Add-prices-to-performance" data-toc-modified-id="Add-prices-to-performance-5.11"><span class="toc-item-num">5.11&nbsp;&nbsp;</span>Add prices to performance</a></span><ul class="toc-item"><li><span><a href="#Separate-out-penny-stocks" data-toc-modified-id="Separate-out-penny-stocks-5.11.1"><span class="toc-item-num">5.11.1&nbsp;&nbsp;</span>Separate out penny stocks</a></span><ul class="toc-item"><li><span><a href="#Get-penny-stock-symbols-to-stay-whole" data-toc-modified-id="Get-penny-stock-symbols-to-stay-whole-5.11.1.1"><span class="toc-item-num">5.11.1.1&nbsp;&nbsp;</span>Get penny stock symbols to stay whole</a></span></li></ul></li></ul></li><li><span><a href="#To-pickle" data-toc-modified-id="To-pickle-5.12"><span class="toc-item-num">5.12&nbsp;&nbsp;</span>To pickle</a></span></li><li><span><a href="#Post-to-SQL" data-toc-modified-id="Post-to-SQL-5.13"><span class="toc-item-num">5.13&nbsp;&nbsp;</span>Post to SQL</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Separate-out-penny-stocks" data-toc-modified-id="Separate-out-penny-stocks-5.13.0.1"><span class="toc-item-num">5.13.0.1&nbsp;&nbsp;</span>Separate out penny stocks</a></span></li><li><span><a href="#Performance" data-toc-modified-id="Performance-5.13.0.2"><span class="toc-item-num">5.13.0.2&nbsp;&nbsp;</span>Performance</a></span></li><li><span><a href="#Penny" data-toc-modified-id="Penny-5.13.0.3"><span class="toc-item-num">5.13.0.3&nbsp;&nbsp;</span>Penny</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Company" data-toc-modified-id="Company-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Company</a></span></li><li><span><a href="#Analyst" data-toc-modified-id="Analyst-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Analyst</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Loc-relevant-symbols" data-toc-modified-id="Loc-relevant-symbols-7.0.1"><span class="toc-item-num">7.0.1&nbsp;&nbsp;</span>Loc relevant symbols</a></span></li><li><span><a href="#Loc-relevant-date" data-toc-modified-id="Loc-relevant-date-7.0.2"><span class="toc-item-num">7.0.2&nbsp;&nbsp;</span>Loc relevant date</a></span></li><li><span><a href="#Sort-old-index" data-toc-modified-id="Sort-old-index-7.0.3"><span class="toc-item-num">7.0.3&nbsp;&nbsp;</span>Sort old index</a></span></li><li><span><a href="#Add-last-real-day-to-df_analyst-for-interpolating" data-toc-modified-id="Add-last-real-day-to-df_analyst-for-interpolating-7.0.4"><span class="toc-item-num">7.0.4&nbsp;&nbsp;</span>Add last real day to df_analyst for interpolating</a></span></li></ul></li><li><span><a href="#Create-new" data-toc-modified-id="Create-new-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Create new</a></span><ul class="toc-item"><li><span><a href="#Sort-index" data-toc-modified-id="Sort-index-7.1.1"><span class="toc-item-num">7.1.1&nbsp;&nbsp;</span>Sort index</a></span></li><li><span><a href="#Iterate-to-map-and-fillna" data-toc-modified-id="Iterate-to-map-and-fillna-7.1.2"><span class="toc-item-num">7.1.2&nbsp;&nbsp;</span>Iterate to map and fillna</a></span></li><li><span><a href="#Convert-string-to-float" data-toc-modified-id="Convert-string-to-float-7.1.3"><span class="toc-item-num">7.1.3&nbsp;&nbsp;</span>Convert string to float</a></span></li></ul></li><li><span><a href="#Add-to-sql-server" data-toc-modified-id="Add-to-sql-server-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Add to sql server</a></span></li><li><span><a href="#Pickle" data-toc-modified-id="Pickle-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>Pickle</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Sort-by-date/sym" data-toc-modified-id="Sort-by-date/sym-7.3.0.1"><span class="toc-item-num">7.3.0.1&nbsp;&nbsp;</span>Sort by date/sym</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Combine-company,-analyst-and-performance" data-toc-modified-id="Combine-company,-analyst-and-performance-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Combine company, analyst and performance</a></span><ul class="toc-item"><li><span><a href="#Performance" data-toc-modified-id="Performance-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>Performance</a></span></li><li><span><a href="#Penny" data-toc-modified-id="Penny-8.2"><span class="toc-item-num">8.2&nbsp;&nbsp;</span>Penny</a></span></li><li><span><a href="#Write-pickles" data-toc-modified-id="Write-pickles-8.3"><span class="toc-item-num">8.3&nbsp;&nbsp;</span>Write pickles</a></span></li></ul></li><li><span><a href="#Post-to-firebase" data-toc-modified-id="Post-to-firebase-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Post to firebase</a></span></li></ul></div>

# Introduction

> Can be sped up by only filling from the last date, rather than filling from the entire previous data. The to_be_added_x could simply be added onto the old before pickling
>
> **This is a similar process to the pull and clean data, although measures have been taken to speed it up such as:**
> * Only adding in one day, vs resetting all of the data
> * Only comparing new data to one previous day for interpolation.
> * Using previous indexes, so price creation only loops through 2000+ symbols vs 8000+ before
> * For firebase updating with sym/col/date = x  rather than attempting to upload a dictionary every 100 symbols before

## Style

In [1]:
import warnings
import matplotlib as mpl
mpl.rcParams['axes.titlesize']='xx-large'
mpl.rcParams['xtick.labelsize'] = 13
mpl.rcParams['ytick.labelsize'] = 13
mpl.rcParams['axes.labelsize'] = 16

# Styling notebook
from IPython.core.display import HTML
def css_styling():
    styles = open("./styles/custom.css", "r").read()
    return HTML(styles)
css_styling()

## Imports and data

In [2]:
USE_GPU = True
IGNORE_WARN = True
SEED = 42

import os
import sys
import time
import datetime
import importlib
import pandas as pd
import matplotlib.pyplot as plt
pd.set_option('display.float_format', lambda x: '%.3f' % x)

# Imports for reproducability
import numpy as np
np.random.seed(SEED)

import tensorflow as tf
tf.random.set_seed(SEED)

if 'mlframe' in sys.modules:
    importlib.reload(sys.modules['mlframe'])
    importlib.reload(sys.modules['db'])

from db import DataBase
from mlframe import MLFrame

# Ignore warnings
if IGNORE_WARN:
    warnings.filterwarnings('ignore')

For convinent loading 'from mlframe import MLFrame

C:\Users\12147\anaconda3\envs\tf-gpu\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.metrics.classification module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)

## Load from SQL
> This could be sped up by only selecting the new dates or dates not in stock_cleaned

In [3]:
db = DataBase('stock', 14333, 'localhost')
db.cur.execute(
"""
SHOW TABLES
""")
db_names = list(table[0] for table in db.cur.fetchall())
db.pull_names_as_dataframes(db_names)
db.conn.close()

## Load old data from pickles

In [4]:
old_df_prices = pd.read_pickle("./data/prices.pkl")
old_df_performance = pd.read_pickle('./data/performance.pkl')
old_df_penny_performance = pd.read_pickle('./data/penny_performance.pkl')
old_df_analyst = pd.read_pickle('./data/analyst.pkl')
df_company = pd.read_pickle('./data/company.pkl')

# Test

In [5]:
original = pd.DataFrame({
    'date': [1, 2, 1, 2, 1, 2],
    'sym': ['A', 'A', 'B', 'B', 'C', 'C'],
    'price': [10, 20, 10, 20, 10, 20]
}).set_index('date', drop=True)

new = pd.DataFrame({
    'date': [1, 2, 3, 1, 2, 1, 2, 3],
    'sym': ['A', 'A', 'A', 'B', 'B', 'C', 'C', 'C'],
    'price': [10, 20, 30, 10, 20, 10, 20, 30]  
}).set_index('date', drop=True)

In [6]:
display(original, new)

     sym  price
date
1      A     10
2      A     20
1      B     10
2      B     20
1      C     10
2      C     20

     sym  price
date
1      A     10
2      A     20
3      A     30
1      B     10
2      B     20
1      C     10
2      C     20
3      C     30

In [7]:
expected = pd.DataFrame({
    'date': [3, 3, 3],
    'sym': ['A', 'B', 'C'],
    'price': [30, np.NaN, 30]  
}).set_index('date', drop=True)
expected

     sym  price
date
3      A 30.000
3      B    nan
3      C 30.000

In [8]:
symbols = original['sym'].unique()
idx = [1, 2, 3]
sym_dfs = []
for sym in symbols:
    _new = new.loc[new['sym'] == sym]
    new_sym = pd.DataFrame(_new, index=idx)
    new_sym['sym'] = new_sym['sym'].fillna(method='ffill')
    new_sym['price'] = new_sym['price'].interpolate('pchip')  # fill with predicted value here
    sym_dfs.append(new_sym)
all_new = pd.concat(sym_dfs)
all_new.loc[all_new.index==3]

  sym  price
3   A 30.000
3   B 30.000
3   C 30.000

# Prices

## Clean

In [9]:
# Cleaning first blank row
df_prices = db.frames['prices'].copy(deep=True).drop(0)

# Resetting date index and dropping index
df_prices.set_index('date', inplace=True, drop=True)

print("Null values = \n", df_prices.isna().sum())

Null values =
 sym      0
price    0
dtype: int64

## Create new index, and diff
> * `newest_date` is the most recent date added to the server
> * `date_idx` is the old date index i.e data that doesn't need to be updated
> * `new_idx` is the new date index
> * `idx_diff` is the day(s) that are being added and one day of the previous

In [ ]:
assert(False) # Incorporate drop index
drop_index = pd.to_datetime(['2019-12-09', '2020-06-23', '2020-06-24', '2020-06-25'])

In [10]:
newest_date = df_prices.index.max()
newest_date

datetime.date(2020, 12, 8)

In [11]:
date_idx = old_df_prices.reset_index().query("sym == 'AAPL'")['date'].values
date_idx[:5], date_idx[-5:]

(array(['2019-08-09T00:00:00.000000000', '2019-08-12T00:00:00.000000000',
        '2019-08-13T00:00:00.000000000', '2019-08-14T00:00:00.000000000',
        '2019-08-15T00:00:00.000000000'], dtype='datetime64[ns]'),
 array(['2020-12-02T00:00:00.000000000', '2020-12-03T00:00:00.000000000',
        '2020-12-04T00:00:00.000000000', '2020-12-07T00:00:00.000000000',
        '2020-12-08T00:00:00.000000000'], dtype='datetime64[ns]'))

In [12]:
new_idx = pd.date_range(date_idx[0], newest_date, freq='B')
new_idx[:2], new_idx[-2:]

(DatetimeIndex(['2019-08-09', '2019-08-12'], dtype='datetime64[ns]', freq='B'),
 DatetimeIndex(['2020-12-07', '2020-12-08'], dtype='datetime64[ns]', freq='B'))

In [13]:
idx_diff = pd.date_range(date_idx[-1], newest_date, freq='B')[1:]
idx_diff

DatetimeIndex([], dtype='datetime64[ns]', freq='B')

## Reindex Price

```python
symbols = original['sym'].unique()
idx = [1, 2, 3]
sym_dfs = []
for sym in symbols:
    _og = original.loc[original['sym'] == sym]
    _new = new.loc[new['sym'] == sym]
    new_sym = pd.DataFrame(_new, index=idx)
    new_sym['sym'] = new_sym['sym'].fillna(method='ffill')
    new_sym['price'] = new_sym['price'].interpolate('pchip')  # fill with predicted value here
    sym_dfs.append(new_sym)
all_new = pd.concat(sym_dfs)
all_new.loc[all_new.index==3]
```

In [14]:
old_df_performance = pd.concat([old_df_performance, old_df_penny_performance])

In [15]:
all_symbols = old_df_performance.reset_index()['sym'].unique()
len(all_symbols)

2107

In [16]:
df_prices = df_prices.loc[df_prices['sym'].isin(all_symbols)]
df_new_prices = df_prices.copy()
df_new_prices.index = pd.to_datetime(df_new_prices.index)
df_new_prices = df_new_prices.loc[df_new_prices.index.isin(new_idx)]

In [17]:
symbols = all_symbols
idx = new_idx
sym_dfs = []
for sym in symbols:
    _new = df_new_prices.loc[df_new_prices['sym'] == sym]
    new_sym = pd.DataFrame(_new, index=idx)
    new_sym['sym'] = new_sym['sym'].fillna(method='ffill')
    new_sym['price'] = pd.to_numeric(new_sym['price']).interpolate('pchip')
    sym_dfs.append(new_sym)
all_new = pd.concat(sym_dfs)
to_be_added_prices = all_new.loc[all_new.index.isin(idx_diff)]

In [18]:
df_test = to_be_added_prices.reset_index().copy()
missing_idx = df_test[~((df_test['sym']).isin(df_new_prices['sym']))]

In [19]:
to_be_added_prices.isna().sum()

sym      0
price    0
dtype: int64

In [20]:
df_price = to_be_added_prices
to_be_added_prices.head()

Empty DataFrame
Columns: [sym, price]
Index: []

In [21]:
all_new.isna().sum()

sym      0
price    0
dtype: int64

## Post to SQL

In [22]:
df_prices = to_be_added_prices.reset_index()
df_prices.columns = ['date', 'sym', 'price']
df_prices = df_prices.set_index(['sym', 'date'], drop=True)

In [23]:
# Open database cleaned
db_clean = DataBase('stock_cleaned', 14333, 'localhost')
db_clean.pull_names_as_dataframes(['prices'])
db_clean.frames['prices']

# Make list of queries to post to sql
query_list = []
for idx, row in df_prices.reset_index().iterrows():
    query_list.append(tuple(row.to_dict().values()))

# Execute query
db_clean.cur.executemany("""
INSERT INTO prices (sym, date, price)
VALUES (%s, %s, %s)""",
      query_list)

# Commit
db_clean.conn.commit()

# Close db
db_clean.conn.close()

In [24]:
old_df_performance

,date,sym,RevenueTTM,TotalCash,ExDividendDate,Dividend,DividendYield,PriceToBook,PriceToSales,EnterpriseValue,...,PE,ReturnonEquity,FreeCashFlow,TotalDebtToEquity,PricePerformance52Weeks,PricePerformanceYTD,TotalReturn1Yr,TotalReturn3Yr,VolumeAvg90Day,price
0,2019-08-09,A,5019.000,2155.000,0.000,0.164,0.944,4.298,4.402,21670704590.000,...,19.800,23.160,887.000,37.290,3.131,3.009,4.044,14.794,2.593,68.640
1,2019-08-12,A,5019.000,2155.000,0.000,0.164,0.956,4.246,4.348,21401262240.000,...,19.200,23.160,887.000,37.290,3.592,1.749,4.508,14.099,2.585,66.780
2,2019-08-13,A,5019.000,2155.000,0.000,0.164,0.985,4.121,4.221,20764110330.000,...,19.500,23.160,887.000,37.290,0.558,-1.230,1.448,12.479,2.605,67.640
3,2019-08-14,A,5019.000,2155.000,0.000,0.164,0.970,4.184,4.285,21084271240.000,...,18.900,23.160,887.000,37.290,2.578,0.267,3.485,13.044,2.616,65.590
4,2019-08-15,A,5090.000,1765.000,0.000,0.164,1.000,4.283,4.068,20365900000.000,...,20.800,22.018,918.000,36.935,-1.738,-2.772,-0.869,11.891,2.631,69.590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
722394,2020-12-01,ZEST,6.093,1.664,0.000,0.000,0.000,10.371,25.656,188952250.000,...,0.000,-415.840,-10.466,143.253,37.795,93.242,37.795,-15.202,0.304,1.750
722395,2020-12-02,ZEST,6.093,1.664,0.000,0.000,0.000,10.371,25.656,188952250.000,...,0.000,-415.840,-10.466,143.253,37.795,93.242,37.795,-15.004,0.303,1.770
722396,2020-12-03,ZEST,6.093,1.664,0.000,0.000,0.000,10.489,25.949,191060870.000,...,0.000,-415.840,-10.466,143.253,36.154,95.451,36.154,-14.682,0.305,1.740
722397,2020-12-04,ZEST,6.093,1.664,0.000,0.000,0.000,10.311,25.509,187897940.000,...,0.000,-415.840,-10.466,143.253,39.200,92.138,39.200,-15.166,0.300,1.700
722398,2020-12-07,ZEST,6.093,1.664,0.000,0.000,0.000,10.074,24.923,183680700.000,...,0.000,-415.840,-10.466,143.253,47.826,87.721,47.826,-15.821,0.298,1.730

## To pickle

In [25]:
all_new = all_new.reset_index()
all_new.columns = ['date', 'sym', 'price']

In [26]:
all_new = all_new.set_index('date', drop=True)

In [27]:
all_new.to_pickle("./data/prices.pkl")
(all_new != pd.read_pickle("./data/prices.pkl")).sum()

sym      0
price    0
dtype: int64

## Reset prices

In [23]:
df_prices = pd.read_pickle("./data/prices.pkl")
df_prices = df_prices.reset_index().set_index(['date'])
df_prices.index = pd.to_datetime(df_prices.index)

In [24]:
df_prices['sym'].nunique()

2107

# Check for new splits

In [25]:
df_splits = db.frames['splits']

In [26]:
idx_diff

DatetimeIndex([], dtype='datetime64[ns]', freq='B')

In [27]:
assert(df_splits['execute'].isin(idx_diff).sum() == 0)

# Performance
> **Steps to take**
> * Load in performance, and clean
> * Match index to prices
> * Try to interpolate null values by one day as we did with prices
> * Fill null ExDividend dates with 1970-01-01 then encode days since then for numerical data
> * Decide what columns to drop, and which stocks to drop if they are in a given column
> * Apply splits
> * Post to sql server  CHECKPOINT
> * Drop penny stocks ~1/5 of data

## Functions

In [4]:
def get_perc_not_null(df):
    """Returns the percentages of null in each column to the length of the df"""
    nulls = df.isna().sum()
    return pd.Series(1 - nulls/len(df)).sort_values() * 100

In [5]:
def check_quantity_stocks_null_in_columns(df, cols):
    """Query to find how many stocks have a null value in any of these columns
        loc the rows that have any nulls in the given columns
        reset the index to 0-x
        get 'sym' series
        get the number of unique values
        """
    return df.loc[df[cols].isna().transpose().any()].reset_index()['sym'].nunique()

In [6]:
def try_replace(x):
    """Quick fix to some of the data having '1,300' instead of a number"""
    try:
        x = x.replace(',', '')
        return x
    except Exception:
        return x

In [31]:
drop_cols = ['PEG', 'FwdEPS3to5Yr', 'DividendCoverage', 'TotalReturn10Yr',
             'EPSGrowth5Year', 'TotalReturn5Yr']

## Sort old index old

In [32]:
old_df_performance = old_df_performance.set_index(['sym', 'date'], drop=True).sort_index().reset_index().set_index(['date'], drop=True)

In [33]:
old_df_performance

,sym,RevenueTTM,TotalCash,ExDividendDate,Dividend,DividendYield,PriceToBook,PriceToSales,EnterpriseValue,PriceToCashFlow,PE,ReturnonEquity,FreeCashFlow,TotalDebtToEquity,PricePerformance52Weeks,PricePerformanceYTD,TotalReturn1Yr,TotalReturn3Yr,VolumeAvg90Day,price
date,,,,,,,,,,,,,,,,,,,,
2019-08-09,A,5019.000,2155.000,0.000,0.164,0.944,4.298,4.402,21670704590.000,16.574,19.800,23.160,887.000,37.290,3.131,3.009,4.044,14.794,2.593,68.640
2019-08-12,A,5019.000,2155.000,0.000,0.164,0.956,4.246,4.348,21401262240.000,16.371,19.200,23.160,887.000,37.290,3.592,1.749,4.508,14.099,2.585,66.780
2019-08-13,A,5019.000,2155.000,0.000,0.164,0.985,4.121,4.221,20764110330.000,15.892,19.500,23.160,887.000,37.290,0.558,-1.230,1.448,12.479,2.605,67.640
2019-08-14,A,5019.000,2155.000,0.000,0.164,0.970,4.184,4.285,21084271240.000,16.132,18.900,23.160,887.000,37.290,2.578,0.267,3.485,13.044,2.616,65.590
2019-08-15,A,5090.000,1765.000,0.000,0.164,1.000,4.283,4.068,20365900000.000,16.051,20.800,22.018,918.000,36.935,-1.738,-2.772,-0.869,11.891,2.631,69.590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-02,ZYXI,68.679,41.229,0.000,0.000,0.000,8.596,6.558,430813280.000,39.293,43.700,32.881,3.825,17.030,28.000,70.775,28.000,77.184,0.803,13.120
2020-12-03,ZYXI,68.679,41.229,0.000,0.000,0.000,8.404,6.411,420392180.000,38.416,45.100,32.881,3.825,17.030,31.663,66.963,31.663,75.855,0.797,13.530
2020-12-04,ZYXI,68.679,41.229,0.000,0.000,0.000,8.654,6.602,433939610.000,39.557,47.100,32.881,3.825,17.030,26.331,71.919,26.331,77.578,0.781,14.130
2020-12-07,ZYXI,68.679,41.229,0.000,0.000,0.000,9.037,6.894,454781810.000,41.311,46.000,32.881,3.825,17.030,41.300,79.543,41.300,92.600,0.776,13.800
2020-12-08,ZYXI,68.679,41.229,0.000,0.000,0.000,8.826,6.733,443318600.000,40.346,46.200,32.881,3.825,17.030,37.313,75.349,37.313,78.155,0.747,13.850

## load in data

In [34]:
# Cleaning first two blank rows
df_performance = db.frames['performance'].copy(deep=True).drop([0, 1])

# Drop cols
df_performance.drop(drop_cols, inplace=True, axis=1)

# Remove Dates that are less than august 8th, as that is from a different collection method
df_performance = df_performance[df_performance['date'] > pd.to_datetime('2019-08-08')]

# Resetting date index and dropping index
df_performance.set_index('date', inplace=True, drop=True)

# Dropping null date values
df_performance = df_performance.loc[df_performance.index.notnull()]

# Replace -- with NaN
df_performance.replace(['', '--'], np.NaN, inplace=True)
df_performance.head()

,sym,MCAP,RevenueTTM,TotalCash,ExDividendDate,Dividend,DividendYield,PriceToBook,PriceToSales,EnterpriseValue,...,PE,ReturnonEquity,FreeCashFlow,TotalDebtToEquity,PricePerformance52Weeks,PricePerformanceYTD,TotalReturn1Yr,TotalReturn3Yr,SharesOutstanding,VolumeAvg90Day
date,,,,,,,,,,,,,,,,,,,,,
2019-08-09,A,22027.70459,5019,2155,NaN,0.164,0.94402,4.29809,4.40182,21670704590,...,19.8,23.1598,887,37.29007,3.13149,3.00919,4.04369,14.79356,315.993,2.59274
2019-08-12,A,21758.26224,5019,2155,NaN,0.164,0.95571,4.24551,4.34797,21401262240,...,19.2,23.1598,887,37.29007,3.59191,1.74918,4.50818,14.09856,315.993,2.58484
2019-08-13,A,21121.11033,5019,2155,NaN,0.164,0.98454,4.12119,4.22065,20764110330,...,19.5,23.1598,887,37.29007,0.55841,-1.23036,1.44784,12.4788,315.993,2.60485
2019-08-14,A,21441.27124,5019,2155,NaN,0.164,0.96984,4.18366,4.28463,21084271240,...,18.9,23.1598,887,37.29007,2.5781,0.26682,3.4854,13.04428,315.993,2.61616
2019-08-15,A,20332.9,5090,1765,NaN,0.164,1.00015,4.28332,4.06782,20365900000,...,20.8,22.0179,918,36.93453,-1.73783,-2.77201,-0.8687,11.89052,315.993,2.63078

### Loc relevant symbols

In [35]:
df_performance = df_performance.loc[df_performance['sym'].isin(all_symbols)]

## Pull out new data

In [36]:
df_performance.index = pd.to_datetime(df_performance.index)

In [37]:
df_performance = df_performance.loc[df_performance.index.isin(df_performance.iloc[-(len(idx_diff))::].index)]
df_performance

,sym,MCAP,RevenueTTM,TotalCash,ExDividendDate,Dividend,DividendYield,PriceToBook,PriceToSales,EnterpriseValue,...,PE,ReturnonEquity,FreeCashFlow,TotalDebtToEquity,PricePerformance52Weeks,PricePerformanceYTD,TotalReturn1Yr,TotalReturn3Yr,SharesOutstanding,VolumeAvg90Day
date,,,,,,,,,,,,,,,,,,,,,
2019-08-09,A,22027.70459,5019,2155,NaN,0.164,0.94402,4.29809,4.40182,21670704590,...,19.8,23.1598,887,37.29007,3.13149,3.00919,4.04369,14.79356,315.993,2.59274
2019-08-12,A,21758.26224,5019,2155,NaN,0.164,0.95571,4.24551,4.34797,21401262240,...,19.2,23.1598,887,37.29007,3.59191,1.74918,4.50818,14.09856,315.993,2.58484
2019-08-13,A,21121.11033,5019,2155,NaN,0.164,0.98454,4.12119,4.22065,20764110330,...,19.5,23.1598,887,37.29007,0.55841,-1.23036,1.44784,12.4788,315.993,2.60485
2019-08-14,A,21441.27124,5019,2155,NaN,0.164,0.96984,4.18366,4.28463,21084271240,...,18.9,23.1598,887,37.29007,2.5781,0.26682,3.4854,13.04428,315.993,2.61616
2019-08-15,A,20332.9,5090,1765,NaN,0.164,1.00015,4.28332,4.06782,20365900000,...,20.8,22.0179,918,36.93453,-1.73783,-2.77201,-0.8687,11.89052,315.993,2.63078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-02,ZYXI,466.86528,68.679,41.229,NaN,NaN,NaN,8.59615,6.55777,430813280,...,43.7,32.8813,3.825,17.03027,28,70.7751,28,77.18351,34.741,0.80346
2020-12-03,ZYXI,456.44418,68.679,41.229,NaN,NaN,NaN,8.40427,6.41139,420392180,...,45.1,32.8813,3.825,17.03027,31.66333,66.96315,31.66333,75.85525,34.741,0.79738
2020-12-04,ZYXI,469.99161,68.679,41.229,NaN,NaN,NaN,8.65371,6.60168,433939610,...,47.1,32.8813,3.825,17.03027,26.33053,71.91868,26.33053,77.57812,34.741,0.78071
2020-12-07,ZYXI,490.83381,68.679,41.229,NaN,NaN,NaN,9.03747,6.89444,454781810,...,46.0,32.8813,3.825,17.03027,41.3,79.54257,41.3,92.59992,34.741,0.77601
2020-12-08,ZYXI,479.3706,68.679,41.229,NaN,NaN,NaN,8.8264,6.73343,443318600,...,46.2,32.8813,3.825,17.03027,37.31343,75.34943,37.31343,78.15494,34.741,0.74735

## Fill ExDividendDate and map

In [38]:
fill_date = pd.to_datetime('1970-01-01')
df_performance = df_performance.reset_index().set_index('date', drop=True)
df_performance['ExDividendDate'] = pd.to_datetime(df_performance['ExDividendDate'].fillna(fill_date))
print("Null dates:", df_performance['ExDividendDate'].isna().sum())
df_performance['ExDividendDate'] = \
    df_performance['ExDividendDate'].map(lambda x: (x - fill_date).days)
df_performance.head()

Null dates: 0

,sym,MCAP,RevenueTTM,TotalCash,ExDividendDate,Dividend,DividendYield,PriceToBook,PriceToSales,EnterpriseValue,...,PE,ReturnonEquity,FreeCashFlow,TotalDebtToEquity,PricePerformance52Weeks,PricePerformanceYTD,TotalReturn1Yr,TotalReturn3Yr,SharesOutstanding,VolumeAvg90Day
date,,,,,,,,,,,,,,,,,,,,,
2019-08-09,A,22027.70459,5019,2155,0,0.164,0.94402,4.29809,4.40182,21670704590,...,19.8,23.1598,887,37.29007,3.13149,3.00919,4.04369,14.79356,315.993,2.59274
2019-08-12,A,21758.26224,5019,2155,0,0.164,0.95571,4.24551,4.34797,21401262240,...,19.2,23.1598,887,37.29007,3.59191,1.74918,4.50818,14.09856,315.993,2.58484
2019-08-13,A,21121.11033,5019,2155,0,0.164,0.98454,4.12119,4.22065,20764110330,...,19.5,23.1598,887,37.29007,0.55841,-1.23036,1.44784,12.4788,315.993,2.60485
2019-08-14,A,21441.27124,5019,2155,0,0.164,0.96984,4.18366,4.28463,21084271240,...,18.9,23.1598,887,37.29007,2.5781,0.26682,3.4854,13.04428,315.993,2.61616
2019-08-15,A,20332.9,5090,1765,0,0.164,1.00015,4.28332,4.06782,20365900000,...,20.8,22.0179,918,36.93453,-1.73783,-2.77201,-0.8687,11.89052,315.993,2.63078

## Find and clean new values

In [39]:
for col in df_performance.head().columns:
    df_performance[col] = df_performance[col].map(try_replace)

## To numeric

In [40]:
for col in df_performance.columns:
    if col != 'sym':
        df_performance[col] = pd.to_numeric(df_performance[col])

## Add last real day to df_performance for interpolating

In [41]:
old_df_performance = old_df_performance.loc[old_df_performance.index[-1] == (old_df_performance.index)]
old_df_performance

,sym,RevenueTTM,TotalCash,ExDividendDate,Dividend,DividendYield,PriceToBook,PriceToSales,EnterpriseValue,PriceToCashFlow,PE,ReturnonEquity,FreeCashFlow,TotalDebtToEquity,PricePerformance52Weeks,PricePerformanceYTD,TotalReturn1Yr,TotalReturn3Yr,VolumeAvg90Day,price
date,,,,,,,,,,,,,,,,,,,,
2020-12-08,A,5339.000,1441.000,18631.000,0.194,0.678,7.184,6.605,35924400000.000,34.337,50.900,14.771,802.000,52.378,39.156,34.099,40.348,20.750,1.421,117.010
2020-12-08,AAL,24622.000,8792.000,0.000,0.100,3.331,74.794,0.326,41166074840.000,2.964,3.200,219.823,-6029.000,-1299.197,-37.926,-39.993,-37.698,-29.728,70.719,17.630
2020-12-08,AAMC,4.127,44.909,0.000,0.000,0.000,0.000,2.262,244170640.000,0.000,0.000,9.698,7.201,-1.627,67.803,90.445,67.803,-31.562,0.013,23.000
2020-12-08,AAME,187.705,9.959,0.000,0.020,1.117,0.343,0.234,84041000.000,15.863,35.800,1.011,4.646,33.247,9.694,9.137,9.694,-14.595,0.011,2.150
2020-12-08,AAP,9853.804,1068.205,18613.000,0.250,0.651,2.796,1.076,12940901600.000,14.548,22.200,13.089,674.044,100.361,-0.608,-4.046,0.039,16.720,0.858,152.780
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-08,ZIXI,210.990,23.662,0.000,0.000,0.000,12.132,2.049,720383960.000,17.170,0.000,-40.690,12.460,520.213,9.469,12.537,9.469,21.443,0.773,7.650
2020-12-08,ZNGA,1763.250,755.431,0.000,0.000,0.000,3.402,4.960,9548255130.000,185.081,143.900,-18.134,296.400,34.476,42.719,44.935,42.719,32.420,20.909,8.840
2020-12-08,ZTS,6555.000,3654.000,0.000,0.200,0.505,20.906,11.486,79511253350.000,35.784,45.800,55.226,1523.000,240.880,30.176,19.720,30.921,31.074,1.664,158.990
2020-12-08,ZUMZ,987.869,316.173,0.000,0.000,0.000,1.914,0.970,966967720.000,9.992,13.300,15.283,145.507,72.242,5.751,8.599,5.751,21.045,0.339,37.270
2020-12-08,ZYXI,68.679,41.229,0.000,0.000,0.000,8.826,6.733,443318600.000,40.346,46.200,32.881,3.825,17.030,37.313,75.349,37.313,78.155,0.747,13.850

## Create new

In [42]:
df_new_performance = pd.concat([old_df_performance, df_performance])

### Sort index

In [43]:
df_new_performance = df_new_performance.reset_index().set_index(['sym', 'date'], drop=True).sort_index().reset_index().set_index(['date'], drop=True)
df_new_performance

,sym,RevenueTTM,TotalCash,ExDividendDate,Dividend,DividendYield,PriceToBook,PriceToSales,EnterpriseValue,PriceToCashFlow,...,FreeCashFlow,TotalDebtToEquity,PricePerformance52Weeks,PricePerformanceYTD,TotalReturn1Yr,TotalReturn3Yr,VolumeAvg90Day,price,MCAP,SharesOutstanding
date,,,,,,,,,,,,,,,,,,,,,
2019-08-09,A,5019.000,2155.000,0.000,0.164,0.944,4.298,4.402,21670704590.000,16.574,...,887.000,37.290,3.131,3.009,4.044,14.794,2.593,nan,22027.705,315.993
2019-08-12,A,5019.000,2155.000,0.000,0.164,0.956,4.246,4.348,21401262240.000,16.371,...,887.000,37.290,3.592,1.749,4.508,14.099,2.585,nan,21758.262,315.993
2019-08-13,A,5019.000,2155.000,0.000,0.164,0.985,4.121,4.221,20764110330.000,15.892,...,887.000,37.290,0.558,-1.230,1.448,12.479,2.605,nan,21121.110,315.993
2019-08-14,A,5019.000,2155.000,0.000,0.164,0.970,4.184,4.285,21084271240.000,16.132,...,887.000,37.290,2.578,0.267,3.485,13.044,2.616,nan,21441.271,315.993
2019-08-15,A,5090.000,1765.000,0.000,0.164,1.000,4.283,4.068,20365900000.000,16.051,...,918.000,36.935,-1.738,-2.772,-0.869,11.891,2.631,nan,20332.900,315.993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-03,ZYXI,68.679,41.229,0.000,nan,nan,8.404,6.411,420392180.000,38.416,...,3.825,17.030,31.663,66.963,31.663,75.855,0.797,nan,456.444,34.741
2020-12-04,ZYXI,68.679,41.229,0.000,nan,nan,8.654,6.602,433939610.000,39.557,...,3.825,17.030,26.331,71.919,26.331,77.578,0.781,nan,469.992,34.741
2020-12-07,ZYXI,68.679,41.229,0.000,nan,nan,9.037,6.894,454781810.000,41.311,...,3.825,17.030,41.300,79.543,41.300,92.600,0.776,nan,490.834,34.741
2020-12-08,ZYXI,68.679,41.229,0.000,0.000,0.000,8.826,6.733,443318600.000,40.346,...,3.825,17.030,37.313,75.349,37.313,78.155,0.747,13.850,nan,nan
2020-12-08,ZYXI,68.679,41.229,0.000,nan,nan,8.826,6.733,443318600.000,40.346,...,3.825,17.030,37.313,75.349,37.313,78.155,0.747,nan,479.371,34.741

### Interpolate null values by symbol

In [44]:
# takes symbols and idx from when prices ran through this
symbols = all_symbols
idx = df_new_performance.iloc[-(len(idx_diff)+1)::].index
sym_dfs = []

## Create new

In [45]:
df_new_performance.drop(['MCAP', 'SharesOutstanding'], inplace=True, axis=1)

In [49]:
# takes symbols and idx from when prices ran through this
symbols = all_symbols
idx = df_new_performance.iloc[-(len(idx_diff)+1)::].index
sym_dfs = []

sym_num = len(all_symbols)
times = np.array([])

def cust_interpolate_fill_na(sym):
    # Locing new, and one before for filling to speed up
    _new = df_new_performance.loc[df_new_performance['sym'] == sym]
    new_sym['sym'] = new_sym['sym'].fillna(method='ffill')
    new_sym = new_sym.interpolate()
    sym_dfs.append(new_sym)

for num, sym in enumerate(symbols):
    start = time.time()
    cust_interpolate_fill_na(sym)  # Timed function
    end = time.time()
    time_taken = end-start
    times = np.append(times, time_taken)
    print(f"{num+1}/{sym_num} in {time_taken: .2f}s for {sym} :: averaging {times.mean():.2f}s/sym...", end='\r')
    
all_new = pd.concat(sym_dfs)
to_be_added_performance = all_new.loc[all_new.index.isin(idx_diff)]

,sym,RevenueTTM,TotalCash,ExDividendDate,Dividend,DividendYield,PriceToBook,PriceToSales,EnterpriseValue,PriceToCashFlow,PE,ReturnonEquity,FreeCashFlow,TotalDebtToEquity,PricePerformance52Weeks,PricePerformanceYTD,TotalReturn1Yr,TotalReturn3Yr,VolumeAvg90Day,price
date,,,,,,,,,,,,,,,,,,,,
2019-08-09,A,5019.000,2155.000,0.000,0.164,0.944,4.298,4.402,21670704590.000,16.574,19.800,23.160,887.000,37.290,3.131,3.009,4.044,14.794,2.593,nan
2019-08-12,A,5019.000,2155.000,0.000,0.164,0.956,4.246,4.348,21401262240.000,16.371,19.200,23.160,887.000,37.290,3.592,1.749,4.508,14.099,2.585,nan
2019-08-13,A,5019.000,2155.000,0.000,0.164,0.985,4.121,4.221,20764110330.000,15.892,19.500,23.160,887.000,37.290,0.558,-1.230,1.448,12.479,2.605,nan
2019-08-14,A,5019.000,2155.000,0.000,0.164,0.970,4.184,4.285,21084271240.000,16.132,18.900,23.160,887.000,37.290,2.578,0.267,3.485,13.044,2.616,nan
2019-08-15,A,5090.000,1765.000,0.000,0.164,1.000,4.283,4.068,20365900000.000,16.051,20.800,22.018,918.000,36.935,-1.738,-2.772,-0.869,11.891,2.631,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-03,A,5339.000,1441.000,18631.000,0.194,0.677,7.194,6.615,35976420000.000,34.388,49.400,14.771,802.000,52.378,42.589,34.298,43.810,19.638,1.409,nan
2020-12-04,A,5339.000,1441.000,18631.000,0.194,0.683,7.132,6.558,35673480000.000,34.091,50.100,14.771,802.000,52.378,41.798,33.138,43.013,19.292,1.413,nan
2020-12-07,A,5339.000,1441.000,18631.000,0.194,0.674,7.231,6.648,36153900000.000,34.562,49.700,14.771,802.000,52.378,41.236,34.978,42.447,21.551,1.410,nan
2020-12-08,A,5339.000,1441.000,18631.000,0.194,0.678,7.184,6.605,35924400000.000,34.337,50.900,14.771,802.000,52.378,39.156,34.099,40.348,20.750,1.421,117.010
2020-12-08,A,5339.000,1441.000,18631.000,0.194,0.678,7.184,6.605,35924400000.000,34.337,50.900,14.771,802.000,52.378,39.156,34.099,40.348,20.750,1.421,nan

DatetimeIndex(['2020-12-08'], dtype='datetime64[ns]', name='date', freq=None)

ZeroDivisionError: division by zero

In [ ]:
assert(to_be_added_performance.isna().sum().sum() == 0)
assert(all_new.isna().sum().sum() == 0)

In [51]:
old_df_performance = pd.read_pickle('./data/performance.pkl')
old_df_penny_performance = pd.read_pickle('./data/penny_performance.pkl')
old_df_performance = pd.concat([old_df_performance, old_df_penny_performance])
old_df_performance = old_df_performance.set_index('date', drop=True)

In [ ]:
all_new = pd.concat([old_df_performance, to_be_added_performance])
all_new.tail()

### Sort index on all_new

In [ ]:
all_new = all_new.reset_index().set_index(['sym', 'date'], drop=True).sort_index().reset_index().set_index(['date'], drop=True)
all_new.tail()

In [ ]:
all_new.isna().sum().sum()

## Add prices to performance

In [ ]:
all_new.drop('price', axis=1, inplace=True)

In [ ]:
all_new = all_new.merge(df_prices.reset_index(), on=['date', 'sym'])

In [ ]:
all_new.head()

### Separate out penny stocks

#### Get penny stock symbols to stay whole

In [ ]:
db_clean = DataBase('stock_cleaned', 14333, 'localhost')
db_clean.pull_names_as_dataframes(['penny_performance', 'performance'])
penny_symbols = db_clean.frames['penny_performance']['sym'].unique()
db_clean.conn.close()

In [ ]:
len(penny_symbols)

In [ ]:
all_new_penny = all_new.loc[all_new['sym'].isin(penny_symbols)]

In [ ]:
no_longer_penny = (all_new_penny.loc[all_new_penny['price'] > 1])['sym'].nunique()
print(no_longer_penny, "symbols are no longer less than a dollar")

In [ ]:
all_new = all_new.drop(all_new_penny.index)

In [ ]:
all_new_penny['sym'].nunique()

In [ ]:
all_new['sym'].nunique()

In [ ]:
assert((all_new['sym'].nunique() + all_new_penny['sym'].nunique()) == len(all_symbols))

In [ ]:
len(all_symbols)

## To pickle

In [73]:
all_new_penny.to_pickle('./data/penny_performance.pkl')
assert((all_new_penny != pd.read_pickle('./data/penny_performance.pkl')).sum().sum() == 0)

In [74]:
all_new.to_pickle('./data/performance.pkl')
assert((all_new != pd.read_pickle('./data/performance.pkl')).sum().sum() == 0)

## Post to SQL

#### Separate out penny stocks

In [89]:
to_be_added_performance = to_be_added_performance.reset_index()

In [90]:
to_be_added_performance_penny = to_be_added_performance.loc[to_be_added_performance['sym'].isin(penny_symbols)]

In [93]:
# Make sure this works
to_be_added_performance = to_be_added_performance.drop(to_be_added_performance_penny.index)

#### Performance

In [95]:
db_clean = DataBase('stock_cleaned', 14333, 'localhost')
# Make query list
query_list = []
for idx, row in to_be_added_performance.iterrows():
    query_list.append(tuple(row.to_dict().values()))

# Execute
db_clean.cur.executemany("""
REPLACE INTO performance (date, sym, RevenueTTM, TotalCash, ExDividendDate,
                    Dividend, DividendYield, PriceToBook, PriceToSales,
                    EnterpriseValue, PriceToCashFlow, PE, ReturnonEquity,
                    FreeCashFlow, TotalDebtToEquity, PricePerformance52Weeks,
                    PricePerformanceYTD, TotalReturn1Yr, TotalReturn3Yr,
                    VolumeAvg90Day, price)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
      query_list)

# commit
db_clean.conn.commit()

#### Penny

In [96]:
# Make query list
query_list_penny = []
for idx, row in to_be_added_performance_penny.iterrows():
    query_list_penny.append(tuple(row.to_dict().values()))
    
db_clean.cur.executemany("""
REPLACE INTO penny_performance (date, sym, RevenueTTM, TotalCash, ExDividendDate,
                    Dividend, DividendYield, PriceToBook, PriceToSales,
                    EnterpriseValue, PriceToCashFlow, PE, ReturnonEquity,
                    FreeCashFlow, TotalDebtToEquity, PricePerformance52Weeks,
                    PricePerformanceYTD, TotalReturn1Yr, TotalReturn3Yr,
                    VolumeAvg90Day, price)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
      query_list_penny)

db_clean.conn.commit()

# Company

In [16]:
df_company = db.frames['company'].copy(deep=True)

# Resetting date index and dropping index
df_company.set_index('sym', inplace=True, drop=True)

df_company.drop('date', inplace=True, axis=1)

df_company.replace(['', '--'], np.NaN, inplace=True)
df_company.head()

,company,securityType,sector,industry,subIndustry,Exchange,DJIA,NASDAQ100,SP500
sym,,,,,,,,,
A,Agilent Technologies Inc,CS,Health Care,Life Sciences Tools & Services,Life Sciences Tools & Services,NYSE,0,0,1
AA,Alcoa Corp,CS,Materials,Metals & Mining,Aluminum,NYSE,0,0,0
AABA,Altaba Inc,CS,Consumer Discretionary,Internet & Direct Marketing Retail,Internet & Direct Marketing Retail,NASDAQ,0,0,0
AAC,AAC Holdings Inc,CS,Health Care,Health Care Providers & Services,Health Care Facilities,NYSE,0,0,0
AACG,ATA Creativity Global,DR,Consumer Discretionary,Diversified Consumer Services,Education Services,NASDAQ,0,0,0

In [17]:
df_company = df_company.fillna('unknown')

In [18]:
df_company = df_company[df_company.index.isin(all_symbols)]

NameError: name 'all_symbols' is not defined

In [ ]:
df_company.to_pickle('./data/company.pkl')

# Analyst

In [90]:
# Cleaning first two blank rows
df_analyst = db.frames['analyst'].copy(deep=True).drop([0, 1])

# Resetting date index and dropping index
df_analyst.set_index('date', inplace=True, drop=True)

# Dropping null date values
df_analyst = df_analyst.loc[df_analyst.index.notnull()]

df_analyst.replace(['', '--'], np.NaN, inplace=True)

df_analyst

,sym,Argus,StarMine,ColumbineCapital,FordEquityResearch,ISSEVA,Jefferson,McLeanCapital,NedDavis,TradingCentral,Zacks,SPValuation,SPQuality,SPGrowthStability,SPFinancialHealth,ThomsonReutersVerus,ThomsonReutersIBES
date,,,,,,,,,,,,,,,,,
2019-06-04,A,NaN,NaN,1,3,70,Buy,Neutral,NEUTRAL,NaN,HOLD,92,75,7,85,HOLD,1.714
2019-06-08,A,NaN,NaN,1,3,70,Buy,Neutral,NEUTRAL,NaN,BUY,93,74,6,85,HOLD,1.8
2019-06-17,A,NaN,9.4,1,3,70,1,3,NEUTRAL,3,BUY,93,74,7,85,HOLD,1.813
2019-06-19,A,NaN,9.4,1,3,70,1,3,NEUTRAL,3,HOLD,93,75,7,85,HOLD,1.813
2019-06-20,A,NaN,7,1,3,70,1,3,NEUTRAL,3,HOLD,93,75,7,85,HOLD,1.813
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-02,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,68,15,71,HOLD,1.8
2020-12-03,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,68,15,72,HOLD,1.8
2020-12-04,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,68,15,71,HOLD,1.8
2020-12-07,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,69,14,71,HOLD,1.8
2020-12-08,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,63,68,14,71,HOLD,1.8

### Loc relevant symbols

In [91]:
df_analyst = df_analyst.loc[df_analyst['sym'].isin(all_symbols)]

In [92]:
df_analyst['sym'].nunique()

2107

### Loc relevant date

In [60]:
df_analyst_new = df_analyst.loc[df_analyst.index.isin(df_analyst.iloc[-(len(idx_diff))::].index)]
df_analyst_new

,sym,Argus,StarMine,ColumbineCapital,FordEquityResearch,ISSEVA,Jefferson,McLeanCapital,NedDavis,TradingCentral,Zacks,SPValuation,SPQuality,SPGrowthStability,SPFinancialHealth,ThomsonReutersVerus,ThomsonReutersIBES
date,,,,,,,,,,,,,,,,,
2020-12-08,A,NaN,7.5,NaN,3,70,1,3,NaN,1,NEUTRAL,81,81,31,80,HOLD,2.167
2020-12-08,AAL,Hold,1.5,NaN,5,72,5,3,NaN,3,NEUTRAL,30,22,9,38,HOLD,3.476
2020-12-08,AAMC,NaN,NaN,NaN,NaN,82,NaN,NaN,NaN,NaN,NaN,20,78,92,71,NaN,NaN
2020-12-08,AAME,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,49,16,71,62,HOLD,NaN
2020-12-08,AAP,Buy,7.1,NaN,2,55,1,3,NaN,3,NEUTRAL,68,44,59,82,HOLD,2.333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-08,ZIXI,NaN,7.7,NaN,2,34,3,3,NaN,NaN,NEUTRAL,75,72,49,60,HOLD,1.5
2020-12-08,ZNGA,NaN,2,NaN,3,90,5,3,NaN,3,NEUTRAL,33,33,31,28,HOLD,2.1
2020-12-08,ZTS,Buy,5,NaN,2,56,3,3,NaN,3,NEUTRAL,86,87,58,78,HOLD,2.05
2020-12-08,ZUMZ,NaN,6.3,NaN,2,91,5,3,NaN,NaN,NEUTRAL,88,49,97,68,BUY,2.167
2020-12-08,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,63,68,14,71,HOLD,1.8

In [103]:
old_df_analyst

,sym,Argus,StarMine,ColumbineCapital,FordEquityResearch,ISSEVA,Jefferson,McLeanCapital,NedDavis,TradingCentral,Zacks,SPValuation,SPQuality,SPGrowthStability,SPFinancialHealth,ThomsonReutersVerus,ThomsonReutersIBES
date,,,,,,,,,,,,,,,,,
2019-08-09,A,NaN,5.8,1,3,78,1,3,NEUTRAL,3,HOLD,93,73,6,84,HOLD,2
2019-08-12,A,NaN,8.3,1,3,78,1,3,NEUTRAL,3,BUY,93,73,6,84,HOLD,2
2019-08-13,A,NaN,8.3,1,3,73,1,3,NEUTRAL,3,HOLD,93,73,7,85,HOLD,2
2019-08-14,A,NaN,4.2,1,3,73,1,3,NEUTRAL,3,HOLD,93,73,7,85,HOLD,2
2019-08-15,A,NaN,4.2,1,3,73,1,3,NEUTRAL,3,HOLD,93,74,7,85,HOLD,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-02,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,68,15,71,HOLD,1.8
2020-12-03,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,68,15,72,HOLD,1.8
2020-12-04,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,68,15,71,HOLD,1.8
2020-12-07,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,69,14,71,HOLD,1.8
2020-12-08,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,63,68,14,71,HOLD,1.8

### Sort old index

In [105]:
old_df_analyst = old_df_analyst.reset_index().set_index(['sym', 'date'], drop=True).sort_index().reset_index().set_index(['date'], drop=True)

In [106]:
old_df_analyst

,sym,Argus,StarMine,ColumbineCapital,FordEquityResearch,ISSEVA,Jefferson,McLeanCapital,NedDavis,TradingCentral,Zacks,SPValuation,SPQuality,SPGrowthStability,SPFinancialHealth,ThomsonReutersVerus,ThomsonReutersIBES
date,,,,,,,,,,,,,,,,,
2019-08-09,A,NaN,5.8,1,3,78,1,3,NEUTRAL,3,HOLD,93,73,6,84,HOLD,2
2019-08-12,A,NaN,8.3,1,3,78,1,3,NEUTRAL,3,BUY,93,73,6,84,HOLD,2
2019-08-13,A,NaN,8.3,1,3,73,1,3,NEUTRAL,3,HOLD,93,73,7,85,HOLD,2
2019-08-14,A,NaN,4.2,1,3,73,1,3,NEUTRAL,3,HOLD,93,73,7,85,HOLD,2
2019-08-15,A,NaN,4.2,1,3,73,1,3,NEUTRAL,3,HOLD,93,74,7,85,HOLD,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-02,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,68,15,71,HOLD,1.8
2020-12-03,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,68,15,72,HOLD,1.8
2020-12-04,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,68,15,71,HOLD,1.8
2020-12-07,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,69,14,71,HOLD,1.8
2020-12-08,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,63,68,14,71,HOLD,1.8

### Add last real day to df_analyst for interpolating

In [77]:
old_df_analyst = old_df_analyst.reset_index().set_index(['date'], drop=True)

In [78]:
old_df_analyst = old_df_analyst.loc[old_df_analyst.index[-1] == (old_df_analyst.index)]
old_df_analyst

,sym,Argus,StarMine,ColumbineCapital,FordEquityResearch,ISSEVA,Jefferson,McLeanCapital,NedDavis,TradingCentral,Zacks,SPValuation,SPQuality,SPGrowthStability,SPFinancialHealth,ThomsonReutersVerus,ThomsonReutersIBES
date,,,,,,,,,,,,,,,,,
2020-05-27,A,NaN,6.7,1,3,66,5,3,NEUTRAL,1,NEUTRAL,84,69,0,90,HOLD,2.2
2020-05-27,AAL,Hold,0.6,3,4,0,5,3,SELL,3,NEUTRAL,4,40,4,61,HOLD,3.333
2020-05-27,AAMC,NaN,NaN,3,NaN,82,NaN,NaN,NaN,NaN,NaN,9,10,77,2,NaN,NaN
2020-05-27,AAME,NaN,NaN,2,3,NaN,NaN,NaN,NaN,NaN,NaN,23,20,64,16,HOLD,NaN
2020-05-27,AAP,Buy,1.6,3,3,12,3,3,NEUTRAL,5,NEUTRAL,55,30,6,72,HOLD,2.273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-05-27,ZIXI,NaN,8.4,1,2,23,3,3,NaN,NaN,NEUTRAL,58,37,68,42,HOLD,1.6
2020-05-27,ZNGA,NaN,8.5,1,2,100,5,3,NEUTRAL,1,NEUTRAL,21,34,64,17,HOLD,2.048
2020-05-27,ZTS,Buy,7.2,1,3,64,3,3,BUY,1,NEUTRAL,88,87,67,74,HOLD,2
2020-05-27,ZUMZ,NaN,5.3,2,3,98,1,3,NaN,NaN,NEUTRAL,86,36,99,55,HOLD,2.286
2020-05-27,ZYXI,NaN,8.7,2,2,43,NaN,3,NaN,NaN,NEUTRAL,69,70,51,64,BUY,2

## Create new

In [107]:
df_analyst_new.index = pd.to_datetime(df_analyst_new.index)
old_df_analyst.index = pd.to_datetime(old_df_analyst.index)

In [108]:
df_new_analyst = pd.concat([old_df_analyst, df_analyst_new])

In [111]:
df_new_analyst

,sym,Argus,StarMine,ColumbineCapital,FordEquityResearch,ISSEVA,Jefferson,McLeanCapital,NedDavis,TradingCentral,Zacks,SPValuation,SPQuality,SPGrowthStability,SPFinancialHealth,ThomsonReutersVerus,ThomsonReutersIBES
date,,,,,,,,,,,,,,,,,
2019-08-09,A,NaN,5.8,1,3,78,1,3,NEUTRAL,3,HOLD,93,73,6,84,HOLD,2
2019-08-12,A,NaN,8.3,1,3,78,1,3,NEUTRAL,3,BUY,93,73,6,84,HOLD,2
2019-08-13,A,NaN,8.3,1,3,73,1,3,NEUTRAL,3,HOLD,93,73,7,85,HOLD,2
2019-08-14,A,NaN,4.2,1,3,73,1,3,NEUTRAL,3,HOLD,93,73,7,85,HOLD,2
2019-08-15,A,NaN,4.2,1,3,73,1,3,NEUTRAL,3,HOLD,93,74,7,85,HOLD,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-02,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,68,15,71,HOLD,1.8
2020-12-03,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,68,15,72,HOLD,1.8
2020-12-04,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,68,15,71,HOLD,1.8
2020-12-07,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,69,14,71,HOLD,1.8
2020-12-08,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,63,68,14,71,HOLD,1.8

### Sort index

In [112]:
df_new_analyst = df_new_analyst.reset_index().set_index(['sym', 'date'], drop=True).sort_index().reset_index().set_index(['date'], drop=True)
df_new_analyst

,sym,Argus,StarMine,ColumbineCapital,FordEquityResearch,ISSEVA,Jefferson,McLeanCapital,NedDavis,TradingCentral,Zacks,SPValuation,SPQuality,SPGrowthStability,SPFinancialHealth,ThomsonReutersVerus,ThomsonReutersIBES
date,,,,,,,,,,,,,,,,,
2019-08-09,A,NaN,5.8,1,3,78,1,3,NEUTRAL,3,HOLD,93,73,6,84,HOLD,2
2019-08-12,A,NaN,8.3,1,3,78,1,3,NEUTRAL,3,BUY,93,73,6,84,HOLD,2
2019-08-13,A,NaN,8.3,1,3,73,1,3,NEUTRAL,3,HOLD,93,73,7,85,HOLD,2
2019-08-14,A,NaN,4.2,1,3,73,1,3,NEUTRAL,3,HOLD,93,73,7,85,HOLD,2
2019-08-15,A,NaN,4.2,1,3,73,1,3,NEUTRAL,3,HOLD,93,74,7,85,HOLD,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-02,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,68,15,71,HOLD,1.8
2020-12-03,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,68,15,72,HOLD,1.8
2020-12-04,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,68,15,71,HOLD,1.8
2020-12-07,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,62,69,14,71,HOLD,1.8
2020-12-08,ZYXI,NaN,0.4,NaN,3,42,NaN,3,NaN,NaN,UNDERPERFORM,63,68,14,71,HOLD,1.8

### Iterate to map and fillna

In [113]:
analyst_mapping = {
    'Argus': {0:0, 'Buy':5, 'Hold':3, 'Sell':1,
              5:5, 3:3, 1:1},
    'TradingCentral': {'Buy':5, '1':1, '3':3, '5':5, 0:0, 'Sell':1,
                       1:1, 3:3, 5:5},
    'Jefferson': {'Buy':5, '1':1, '3':3, '5':5, 'Hold':3, 'Sell':1,
                  1:1, 3:3, 5:5},
    'McLeanCapital': {'Buy':5, '1':1, '3':3, '5':5, 'Neutral':3, 'Sell':1,
                      1:1, 3:3, 5:5},
    'NedDavis': {'NEUTRAL':3, 'BUY':5, 'SELL':1,
                 1:1, 3:3, 5:5},
    'Zacks': {'STRONG BUY':6, 'BUY':5, 'OUTPERFORM':5,
             'NEUTRAL':3, 'HOLD':3, 'SELL':2, 'UNDERPERFORM':2,
             'STRONG SELL':1, 'NONE':0,
             1:1, 2:2, 3:3, 5:5, 6:6, 0:0},
    'ThomsonReutersVerus': {'HOLD':3, 'SELL':1, 'BUY':5,
                            1:1, 3:3, 5:5}
}

In [ ]:
assert(False) # Double check analyst, and the column names are whole
assert(False)  # make sure the index matches performance before and after

In [117]:
# takes symbols and idx from when prices ran through this
symbols = all_symbols
idx = df_new_analyst.iloc[-(len(idx_diff)+1)::].index
sym_dfs = []

sym_num = len(symbols)
times = np.array([])

def cust_interpolate_fill_na(sym):
    # Locing new, and one before for filling to speed up
    _new = df_new_analyst.loc[df_new_analyst['sym'] == sym]
    new_sym = pd.DataFrame(_new, index=idx)
    new_sym['sym'] = sym
    new_sym = new_sym.fillna(method='ffill').fillna(0)
    for col, mapping in analyst_mapping.items():
        new_sym[col] = new_sym[col].map(mapping)
    if new_sym.isna().sum().sum() > 0:
        new_sym = new_sym.fillna(0)
    sym_dfs.append(new_sym)

for num, sym in enumerate(symbols):
    start = time.time()
    cust_interpolate_fill_na(sym)  # Timed function
    end = time.time()
    time_taken = end-start
    times = np.append(times, time_taken)
    print(f"{num+1}/{sym_num} in {time_taken: .2f}s for {sym} :: averaging {times.mean():.2f}s/sym...", end='\r')
    
all_new = pd.concat(sym_dfs)
to_be_added_analyst = all_new.loc[all_new.index.isin(idx_diff)]

TypeError: DatetimeIndex() must be called with a collection of some kind, Timestamp('2020-08-12 00:00:00') was passed

In [ ]:
asset(False)# Check index

### Convert string to float

In [120]:
for col in to_be_added_analyst.columns:
    if col != 'sym':
        to_be_added_analyst[col] = pd.to_numeric(to_be_added_analyst[col])
        all_new[col] = pd.to_numeric(all_new[col])

In [121]:
to_be_added_analyst['TradingCentral'].unique()

array([3, 1, 0, 5], dtype=int64)

## Add to sql server

In [8]:
db_clean = DataBase('stock_cleaned', 14333, 'localhost')
db_clean.pull_names_as_dataframes(['analyst'])
db_clean.frames['analyst']

Empty DataFrame
Columns: [sym, date, Argus, StarMine, ColumbineCapital, FordEquityResearch, ISSEVA, Jefferson, McLeanCapital, NedDavis, TradingCentral, Zacks, SPValuation, SPQuality, SPGrowthStability, SPFinancialHealth, ThomsonReutersVerus, ThomsonReutersIBES]
Index: []

In [9]:
query_list = []
for idx, row in to_be_added_analyst.reset_index().iterrows():
    query_list.append(tuple(row.to_dict().values()))

db_clean = DataBase('stock_cleaned', 14333, 'localhost')
db_clean.cur.executemany("""
REPLACE INTO analyst (date, sym, Argus, StarMine, ColumbineCapital,
                         FordEquityResearch, ISSEVA, Jefferson, McLeanCapital,
                         NedDavis, TradingCentral, Zacks, SPValuation,
                         SPQuality, SPGrowthStability, SPFinancialHealth,
                         ThomsonReutersVerus, ThomsonReutersIBES)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
      query_list)
db_clean.conn.commit()
db_clean.conn.close()

## Pickle

In [118]:
assert(False) # Make sure all_new is all of the symbols,  may need to merge with old

AssertionError:

In [124]:
old_df_analyst = pd.read_pickle('./data/analyst.pkl')

In [130]:
all_new = pd.concat([old_df_analyst, all_new]).drop_duplicates()

#### Sort by date/sym

In [133]:
all_new = all_new.reset_index().set_index(['sym', 'date'], drop=True).sort_index().reset_index().set_index(['date'], drop=True)

,sym,Argus,StarMine,ColumbineCapital,FordEquityResearch,ISSEVA,Jefferson,McLeanCapital,NedDavis,TradingCentral,Zacks,SPValuation,SPQuality,SPGrowthStability,SPFinancialHealth,ThomsonReutersVerus,ThomsonReutersIBES
date,,,,,,,,,,,,,,,,,
2019-08-09,A,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0.000,0.000,0.000,0.000,0.000,0.000
2020-12-04,A,0,7.500,1.000,3.000,70.000,1.000,3.000,3.000,1,3,81.000,81.000,32.000,79.000,3.000,2.167
2020-12-07,A,0,7.500,1.000,3.000,70.000,1.000,3.000,3.000,1,3,80.000,80.000,33.000,80.000,3.000,2.167
2020-12-08,A,0,7.500,1.000,3.000,70.000,1.000,3.000,3.000,1,3,81.000,81.000,31.000,80.000,3.000,2.167
2019-08-09,AAL,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0.000,0.000,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-08,ZUMZ,5,6.300,2.000,2.000,91.000,5.000,3.000,3.000,1,3,88.000,49.000,97.000,68.000,5.000,2.167
2019-08-09,ZYXI,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0,0.000,0.000,0.000,0.000,0.000,0.000
2020-12-04,ZYXI,5,0.400,2.000,3.000,42.000,5.000,3.000,3.000,1,2,62.000,68.000,15.000,71.000,3.000,1.800
2020-12-07,ZYXI,5,0.400,2.000,3.000,42.000,5.000,3.000,3.000,1,2,62.000,69.000,14.000,71.000,3.000,1.800
2020-12-08,ZYXI,5,0.400,2.000,3.000,42.000,5.000,3.000,3.000,1,2,63.000,68.000,14.000,71.000,3.000,1.800

In [10]:
all_new = to_be_added_analyst

In [13]:
all_new.to_pickle('./data/analyst.pkl')
assert((all_new != pd.read_pickle('./data/analyst.pkl')).sum().sum() == 0)

# Combine company, analyst and performance

In [14]:
df_prices = pd.read_pickle("./data/prices.pkl")
df_performance = pd.read_pickle('./data/performance.pkl')
df_penny_performance = pd.read_pickle('./data/penny_performance.pkl')
df_analyst = pd.read_pickle('./data/analyst.pkl')

In [25]:
df_company.drop('subIndustry', axis=1, inplace=True)

KeyError: "['subIndustry'] not found in axis"

In [21]:
def combine_df(df, company, analyst):
    ohe_columns = list(company.columns)
    ohe_columns.remove('company')
    df = df.reset_index().set_index(['date', 'sym'], drop=True)
    analyst = analyst.reset_index().set_index(['date', 'sym'], drop=True)
    df_new = MLFrame(df.join(df_company).join(analyst))
    df_new.drop('company', inplace=True, axis=1)
    df_new = df_new.one_hot_encode(columns=ohe_columns)
    return df_new

## Performance

In [39]:
df_performance_combined = combine_df(df_performance, df_company, df_analyst)
df_performance_combined.head()

Added categorical columns
3 -> Dividend
4 -> Exchange
5 -> securityType
10 -> sector
68 -> industry

,,index,RevenueTTM,TotalCash,ExDividendDate,Dividend,DividendYield,PriceToBook,PriceToSales,EnterpriseValue,PriceToCashFlow,...,industry_Transportation Infrastructure,industry_Water Utilities,industry_Wireless Telecommunication Services,Exchange_NASDAQ,Exchange_NYSE,Exchange_OTC,Exchange_unknown,DJIA_1,NASDAQ100_1,SP500_1
date,sym,,,,,,,,,,,,,,,,,,,,,
2019-08-09,A,0,5019.000,2155.000,0.000,0.164,0.944,4.298,4.402,21670704590.000,16.574,...,0,0,0,0,1,0,0,0,0,1
2019-08-12,A,1,5019.000,2155.000,0.000,0.164,0.956,4.246,4.348,21401262240.000,16.371,...,0,0,0,0,1,0,0,0,0,1
2019-08-13,A,2,5019.000,2155.000,0.000,0.164,0.985,4.121,4.221,20764110330.000,15.892,...,0,0,0,0,1,0,0,0,0,1
2019-08-14,A,3,5019.000,2155.000,0.000,0.164,0.970,4.184,4.285,21084271240.000,16.132,...,0,0,0,0,1,0,0,0,0,1
2019-08-15,A,4,5090.000,1765.000,0.000,0.164,1.000,4.283,4.068,20365900000.000,16.051,...,0,0,0,0,1,0,0,0,0,1

## Penny

In [40]:
df_penny_performance_combined = combine_df(df_penny_performance, df_company, df_analyst)
df_penny_performance_combined.head()

Added categorical columns
3 -> Dividend
3 -> securityType
3 -> Exchange
10 -> sector
47 -> industry

,,index,RevenueTTM,TotalCash,ExDividendDate,Dividend,DividendYield,PriceToBook,PriceToSales,EnterpriseValue,PriceToCashFlow,...,industry_Road & Rail,industry_Semiconductors & Semiconductor Equipment,industry_Software,industry_Specialty Retail,"industry_Technology Hardware, Storage & Peripherals","industry_Textiles, Apparel & Luxury Goods",industry_Trading Companies & Distributors,Exchange_NASDAQ,Exchange_NYSE,Exchange_OTC
date,sym,,,,,,,,,,,,,,,,,,,,,
2019-08-09,ACFN,6536,5.205,1.078,0.000,0.000,0.000,0.000,1.746,8486470.000,0.000,...,0,0,0,0,0,0,0,0,0,1
2019-08-12,ACFN,6537,5.205,1.078,0.000,0.000,0.000,0.000,1.526,7344130.600,0.000,...,0,0,0,0,0,0,0,0,0,1
2019-08-13,ACFN,6538,5.205,1.078,0.000,0.000,0.000,0.000,1.135,5309200.000,0.000,...,0,0,0,0,0,0,0,0,0,1
2019-08-14,ACFN,6539,5.205,1.078,0.000,0.000,0.000,0.000,1.553,7484521.600,0.000,...,0,0,0,0,0,0,0,0,0,1
2019-08-15,ACFN,6540,5.205,1.078,0.000,0.000,0.000,0.000,1.646,7969240.000,0.000,...,0,0,0,0,0,0,0,0,0,1

## Write pickles

In [41]:
df_performance_combined.to_pickle('./data/performance_combined.pkl')
df_penny_performance_combined.to_pickle('./data/performance_penny_combined.pkl')

# Post to firebase

```python
# Test

aal = {}
sym_df = df_performance.groupby('sym')
aal = sym_df.get_group('AAL').drop('sym', axis=1).reset_index(drop=True).to_dict()
aal['AAL/Argus/322'] = 7
req = fb.refresh_all_data(aal)
```

> As this tests works, if we want to update a date i.e adding 322 we will have to generate the url for each column/key

In [143]:
from db import FireBase
import json
import os

In [144]:
fb = FireBase()

In [145]:
to_be_added_performance

,date,sym,RevenueTTM,TotalCash,ExDividendDate,Dividend,DividendYield,PriceToBook,PriceToSales,EnterpriseValue,...,PE,ReturnonEquity,FreeCashFlow,TotalDebtToEquity,PricePerformance52Weeks,PricePerformanceYTD,TotalReturn1Yr,TotalReturn3Yr,VolumeAvg90Day,price
0,2020-12-08,A,5339.000,1441.000,18631.000,0.194,0.678,7.184,6.605,35924400000.000,...,50.900,14.771,802.000,52.378,39.156,34.099,40.348,20.750,1.421,114.400
1,2020-12-08,AAL,24622.000,8792.000,0.000,0.100,3.331,74.794,0.326,41166074840.000,...,3.200,219.823,-6029.000,-1299.197,-37.926,-39.993,-37.698,-29.728,70.719,17.210
2,2020-12-08,AAMC,4.127,44.909,0.000,0.000,0.000,0.000,2.262,244170640.000,...,0.000,9.698,7.201,-1.627,67.803,90.445,67.803,-31.562,0.013,23.520
3,2020-12-08,AAME,187.705,9.959,0.000,0.020,1.117,0.343,0.234,84041000.000,...,35.800,1.011,4.646,33.247,9.694,9.137,9.694,-14.595,0.011,2.150
4,2020-12-08,AAP,9853.804,1068.205,18613.000,0.250,0.651,2.796,1.076,12940901600.000,...,22.200,13.089,674.044,100.361,-0.608,-4.046,0.039,16.720,0.858,153.680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1888,2020-12-08,ZIXI,210.990,23.662,0.000,0.000,0.000,12.132,2.049,720383960.000,...,0.000,-40.690,12.460,520.213,9.469,12.537,9.469,21.443,0.773,7.630
1889,2020-12-08,ZNGA,1763.250,755.431,0.000,0.000,0.000,3.402,4.960,9548255130.000,...,143.900,-18.134,296.400,34.476,42.719,44.935,42.719,32.420,20.909,8.870
1890,2020-12-08,ZTS,6555.000,3654.000,0.000,0.200,0.505,20.906,11.486,79511253350.000,...,45.800,55.226,1523.000,240.880,30.176,19.720,30.921,31.074,1.664,158.450
1891,2020-12-08,ZUMZ,987.869,316.173,0.000,0.000,0.000,1.914,0.970,966967720.000,...,13.300,15.283,145.507,72.242,5.751,8.599,5.751,21.045,0.339,37.510
1892,2020-12-08,ZYXI,68.679,41.229,0.000,0.000,0.000,8.826,6.733,443318600.000,...,46.200,32.881,3.825,17.030,37.313,75.349,37.313,78.155,0.747,13.800

In [146]:
to_be_added_performance_penny

,date,sym,RevenueTTM,TotalCash,ExDividendDate,Dividend,DividendYield,PriceToBook,PriceToSales,EnterpriseValue,...,PE,ReturnonEquity,FreeCashFlow,TotalDebtToEquity,PricePerformance52Weeks,PricePerformanceYTD,TotalReturn1Yr,TotalReturn3Yr,VolumeAvg90Day,price
1893,2020-12-08,ACFN,5.723,1.966,0.000,0.000,0.000,25.188,2.109,11248774.000,...,0.000,47.808,-0.190,-112.653,5.822,-16.486,5.822,11.154,0.038,0.309
1894,2020-12-08,ACRX,5.153,43.023,0.000,0.000,0.000,0.000,23.471,206063880.000,...,0.000,85.491,-46.799,-223.802,-21.925,-30.806,-21.925,-12.104,1.512,1.460
1895,2020-12-08,ADMT,3.224,1.575,0.000,0.000,0.000,2.233,2.233,6762228.500,...,0.000,-7.933,-0.235,26.680,-43.351,-46.723,-43.351,-11.966,0.034,0.106
1896,2020-12-08,AERO,61.037,3.830,0.000,0.000,0.000,6.229,1.676,102658440.000,...,17.500,44.422,4.357,24.077,183.810,223.913,183.810,6.601,0.050,2.980
1897,2020-12-08,AIRI,48.933,1.460,0.000,0.000,0.000,3.615,0.830,73739140.000,...,0.000,-19.535,-6.180,271.771,-11.258,-41.739,-11.258,-1.449,0.335,1.340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2102,2020-12-08,XELB,36.865,5.461,0.000,0.000,0.000,0.207,0.537,43332240.000,...,6.400,-7.597,2.692,30.782,-22.388,-30.667,-22.388,-27.240,0.394,1.040
2103,2020-12-08,XPL,0.408,8.574,0.000,0.000,0.000,1.176,69.188,19736055.600,...,0.000,-3.221,-0.970,0.283,86.808,61.846,86.808,-3.808,0.878,0.486
2104,2020-12-08,XTGRF,3.228,7.670,0.000,0.000,0.000,4.655,13.774,37094670.000,...,19.100,26.041,0.887,0.000,158.108,94.898,158.108,80.982,0.018,0.955
2105,2020-12-08,ZDGE,9.470,5.111,0.000,0.000,0.000,5.526,4.784,44499000.000,...,0.000,-7.564,1.363,7.137,128.964,159.740,128.964,12.625,0.626,4.000
2106,2020-12-08,ZEST,6.093,1.664,0.000,0.000,0.000,10.252,25.362,186843630.000,...,0.000,-415.840,-10.466,143.253,44.167,91.034,44.167,-13.359,0.295,1.730

In [147]:
df_post = pd.concat([to_be_added_performance, to_be_added_performance_penny])

In [148]:
fb_index = fb.get_index()

In [149]:
date_range = fb_index['data']['date_range']
date_range

['08-09-2019',
 '08-12-2019',
 '08-13-2019',
 '08-14-2019',
 '08-15-2019',
 '08-16-2019',
 '08-19-2019',
 '08-20-2019',
 '08-21-2019',
 '08-22-2019',
 '08-23-2019',
 '08-26-2019',
 '08-27-2019',
 '08-28-2019',
 '08-29-2019',
 '08-30-2019',
 '09-02-2019',
 '09-03-2019',
 '09-04-2019',
 '09-05-2019',
 '09-06-2019',
 '09-09-2019',
 '09-10-2019',
 '09-11-2019',
 '09-12-2019',
 '09-13-2019',
 '09-16-2019',
 '09-17-2019',
 '09-18-2019',
 '09-19-2019',
 '09-20-2019',
 '09-23-2019',
 '09-24-2019',
 '09-25-2019',
 '09-26-2019',
 '09-27-2019',
 '09-30-2019',
 '10-01-2019',
 '10-02-2019',
 '10-03-2019',
 '10-04-2019',
 '10-07-2019',
 '10-08-2019',
 '10-09-2019',
 '10-10-2019',
 '10-11-2019',
 '10-14-2019',
 '10-15-2019',
 '10-16-2019',
 '10-17-2019',
 '10-18-2019',
 '10-21-2019',
 '10-22-2019',
 '10-23-2019',
 '10-24-2019',
 '10-25-2019',
 '10-28-2019',
 '10-29-2019',
 '10-30-2019',
 '10-31-2019',
 '11-01-2019',
 '11-04-2019',
 '11-05-2019',
 '11-06-2019',
 '11-07-2019',
 '11-08-2019',
 '11-11-2019',
 '11-12-2019',
 '11-13-2019',
 '11-14-2019',
 '11-15-2019',
 '11-18-2019',
 '11-19-2019',
 '11-20-2019',
 '11-21-2019',
 '11-22-2019',
 '11-25-2019',
 '11-26-2019',
 '11-27-2019',
 '11-28-2019',
 '11-29-2019',
 '12-02-2019',
 '12-03-2019',
 '12-04-2019',
 '12-05-2019',
 '12-06-2019',
 '12-10-2019',
 '12-11-2019',
 '12-12-2019',
 '12-13-2019',
 '12-16-2019',
 '12-17-2019',
 '12-18-2019',
 '12-19-2019',
 '12-20-2019',
 '12-23-2019',
 '12-24-2019',
 '12-25-2019',
 '12-26-2019',
 '12-27-2019',
 '12-30-2019',
 '12-31-2019',
 '01-01-2020',
 '01-02-2020',
 '01-03-2020',
 '01-06-2020',
 '01-07-2020',
 '01-08-2020',
 '01-09-2020',
 '01-10-2020',
 '01-13-2020',
 '01-14-2020',
 '01-15-2020',
 '01-16-2020',
 '01-17-2020',
 '01-20-2020',
 '01-21-2020',
 '01-22-2020',
 '01-23-2020',
 '01-24-2020',
 '01-27-2020',
 '01-28-2020',
 '01-29-2020',
 '01-30-2020',
 '01-31-2020',
 '02-03-2020',
 '02-04-2020',
 '02-05-2020',
 '02-06-2020',
 '02-07-2020',
 '02-10-2020',
 '02-11-2020',
 '02-12-2020',
 '02-13-2020',
 '02-14-2020',
 '02-17-2020',
 '02-18-2020',
 '02-19-2020',
 '02-20-2020',
 '02-21-2020',
 '02-24-2020',
 '02-25-2020',
 '02-26-2020',
 '02-27-2020',
 '02-28-2020',
 '03-02-2020',
 '03-03-2020',
 '03-04-2020',
 '03-05-2020',
 '03-06-2020',
 '03-09-2020',
 '03-10-2020',
 '03-11-2020',
 '03-12-2020',
 '03-13-2020',
 '03-16-2020',
 '03-17-2020',
 '03-18-2020',
 '03-19-2020',
 '03-20-2020',
 '03-23-2020',
 '03-24-2020',
 '03-25-2020',
 '03-26-2020',
 '03-27-2020',
 '03-30-2020',
 '03-31-2020',
 '04-01-2020',
 '04-02-2020',
 '04-03-2020',
 '04-06-2020',
 '04-07-2020',
 '04-08-2020',
 '04-09-2020',
 '04-10-2020',
 '04-13-2020',
 '04-14-2020',
 '04-15-2020',
 '04-16-2020',
 '04-17-2020',
 '04-20-2020',
 '04-21-2020',
 '04-22-2020',
 '04-23-2020',
 '04-24-2020',
 '04-27-2020',
 '04-28-2020',
 '04-29-2020',
 '04-30-2020',
 '05-01-2020',
 '05-04-2020',
 '05-05-2020',
 '05-06-2020',
 '05-07-2020',
 '05-08-2020',
 '05-11-2020',
 '05-12-2020',
 '05-13-2020',
 '05-14-2020',
 '05-15-2020',
 '05-18-2020',
 '05-19-2020',
 '05-20-2020',
 '05-21-2020',
 '05-22-2020',
 '05-25-2020',
 '05-26-2020',
 '05-27-2020',
 '05-28-2020',
 '05-29-2020',
 '06-01-2020',
 '06-02-2020',
 '06-03-2020',
 '06-04-2020',
 '06-05-2020',
 '06-08-2020',
 '06-09-2020',
 '06-10-2020',
 '06-11-2020',
 '06-12-2020',
 '06-15-2020',
 '06-16-2020',
 '06-17-2020',
 '06-18-2020',
 '06-19-2020',
 '06-22-2020',
 '06-26-2020',
 '06-29-2020',
 '06-30-2020',
 '07-01-2020',
 '07-02-2020',
 '07-03-2020',
 '07-06-2020',
 '07-07-2020',
 '07-08-2020',
 '07-09-2020',
 '07-10-2020',
 '07-13-2020',
 '07-14-2020',
 '07-15-2020',
 '07-16-2020',
 '07-17-2020',
 '07-20-2020',
 '07-21-2020',
 '07-22-2020',
 '07-23-2020',
 '07-24-2020',
 '07-27-2020',
 '07-28-2020',
 '07-29-2020',
 '07-30-2020',
 '07-31-2020',
 '08-03-2020',
 '08-04-2020',
 '08-05-2020',
 '08-06-2020',
 '08-07-2020',
 '08-10-2020',
 '08-11-2020',
 '08-12-2020',
 '08-13-2020',
 '08-14-2020',
 '08-17-2020',
 '08-18-2020',
 '08-19-2020',
 '08-20-2020',
 '08-21-2020',
 '08-24-2020',
 '08-25-2020',
 '08-26-2020',
 '08-27-2020',
 '08-28-2020',
 '08-31-2020',
 '09-01-2020',
 '09-02-2020',
 '09-03-2020',
 '09-04-2020',
 '09-07-2020',
 '09-08-2020',
 '09-09-2020',
 '09-10-2020',
 '09-11-2020',
 '09-14-2020',
 '09-15-2020',
 '09-16-2020',
 '09-17-2020',
 '09-18-2020',
 '09-21-2020',
 '09-22-2020',
 '09-23-2020',
 '09-24-2020',
 '09-25-2020',
 '09-28-2020',
 '09-29-2020',
 '09-30-2020',
 '10-01-2020',
 '10-02-2020',
 '10-05-2020',
 '10-06-2020',
 '10-07-2020',
 '10-08-2020',
 '10-09-2020',
 '10-12-2020',
 '10-13-2020',
 '10-14-2020',
 '10-15-2020',
 '10-16-2020',
 '10-19-2020',
 '10-20-2020',
 '10-21-2020',
 '10-22-2020',
 '10-23-2020',
 '10-26-2020',
 '10-27-2020',
 '10-28-2020',
 '10-29-2020',
 '10-30-2020',
 '11-02-2020',
 '11-03-2020',
 '11-04-2020',
 '11-05-2020',
 '11-06-2020',
 '11-09-2020',
 '11-10-2020',
 '11-11-2020',
 '11-12-2020',
 '11-13-2020',
 '11-16-2020',
 '11-17-2020',
 '11-18-2020',
 '11-19-2020',
 '11-20-2020',
 '11-23-2020',
 '11-24-2020',
 '11-25-2020',
 '11-26-2020',
 '11-27-2020',
 '11-30-2020',
 '12-01-2020',
 '12-02-2020',
 '12-03-2020',
 '12-04-2020',
 '12-07-2020']

In [155]:
df_post = df_post.set_index('date', drop=True)

In [156]:
new_dates = pd.Series(df_post.index.unique()).map(lambda x: x.strftime("%m-%d-%Y")).values

In [157]:
to_add = {}
for date in new_dates:
    to_add[len(date_range)] = date
    date_range.append(date)

In [158]:
to_add

{343: '12-08-2020'}

In [159]:
to_add.keys()

dict_keys([343])

In [160]:
all_symbols = df_post['sym'].unique()

for val, date in to_add.items():
    sym_df = df_post.loc[date].groupby('sym')

    post = {}
    for sym in all_symbols:
        sym_new = sym_df.get_group(sym).drop('sym', axis=1).reset_index(drop=True).to_dict()
        for key, value in sym_new.items():
             post[f"{sym}/{key}/{val}"] = value[0]
    req = fb.refresh_all_data(post)
    try:
        req['req']
    except KeyError:
        print("REQUEST ERROR")
        print(req['error'])

In [161]:
date_range = pd.Series(date_range).to_dict()
df_post.reset_index(drop=True, inplace=True)
column_index = list(df_post.columns)
column_index.remove('sym')
column_index = dict(zip(range(len(column_index)), column_index))
all_symbols = df_post['sym'].unique()
symbol_index = tuple(all_symbols)
index = {
    'column': column_index,
    'date_range': date_range,
    'stocks': symbol_index
}
req = fb.refresh_index(index)